### PR TITLE
cards test

### PR DESCRIPTION
**Pull request by lazarusA**
cards don't work on first run

css style from cards should  be copied from OhMyCards.jl, fixes should be done there.

### CODE REVIEW

**Comment by asinghvi17** [comment]
Do you have a manifest?  Maybe do the same thing GeoMakie does and add using a vector of packagespecs, that might get around the current CI issue...

**Comment by lazarusA** [comment]
This one works locally with https://github.com/asinghvi17/OhMyCards.jl/pull/4

**Comment by asinghvi17** [comment]
> TemplateDocsVitePress

may need to be either added locally, dev'ed, or removed from Project.  Once I have a working demo page I'll register OhMyCards which should decrease headaches.

**Comment by lazarusA** [comment]
it was removing locally, and before registering, we still need the author badge, after it should be good to go: 

Screenshot 2024-07-22 at 10 17 50

**Pull request merged**
